name: emergency_app
description: Emergency contacts app

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Существующие
  intl: ^0.19.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.2
  geolocator: ^10.1.1
  vibration: ^2.0.0
  cupertino_icons: ^1.0.8
  share_plus: ^10.1.3
  
  # Новые
  supabase_flutter: ^2.8.0
  onesignal_flutter: ^5.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^0.3.0

flutter:
  generate: true
  uses-material-design: true